emoji = {
'Democratic Republic Of The Congo':'🇨🇩',
'French Southern Territories':'🇹🇫',
'People’s Republic of China':'🇨🇳',
'Central African Republic':'🇨🇫',
'Northern Mariana Islands':'🇲🇵',
'United States Of America':'🇺🇸',
'automated teller machine':'🏧',
'information desk person':'💁',
'Bosnia and Herzegovina':'🇧🇦',
'Palestinian Territory':'🇵🇸',
'Sao Tome and Principe':'🇸🇹',
'woman with bunny ears':'👯',
'United Arab Emirates':'🇦🇪',
'closed lock with key':'🔐',
'Antigua and Barbuda':'🇦🇬',
'construction worker':'👷',
'Dominican Republic':'🇩🇴',
'video game monster':'👾',
'golden gate bridge':'🌉',
'bust in silhouette':'👤',
'first quarter moon':'🌓',
'granny smith apple':'🍏',
'smiling with horns':'😈',
'suspension railway':'🚟',
'Equatorial Guinea':'🇬🇶',
'Stars and Stripes':'🇺🇸',
'heavy black heart':'❤',
'american football':'🏈',
'antenna with bars':'📶',
'double bump camel':'🐫',
'cake with candles':'🎂',
'children crossing':'🚸',
'round of applause':'👏',
'convenience store':'🏪',
'last quarter moon':'🌗',
'feats of strength':'💪',
'grevenstein apple':'🍏',
'screaming in fear':'😱',
'year of the horse':'🐎',
'statue of liberty':'🗽',
'american football':'🏈',
'passport control':'🛂',
'chinese new year':'🐉',
'father christmas':'🎅',
'department store':'🏬',
'festivus miracle':'🙌',
'four leaf clover':'🍀',
'high-heeled shoe':'👠',
'high-speed train':'🚄',
'japanese lantern':'🏮',
'magnifying glass':'🔍',
'pencil and paper':'📝',
'suggestive smile':'😏',
'st patrick’s day':'🍀',
'steam locomotive':'🚂',
'triangular ruler':'📐',
'Cayman Islanders':'🇰🇾',
'Papua New Guinea':'🇵🇬',
'American Samoan':'🇦🇸',
'Solomon Islands':'🇸🇧',
'man on the moon':'🌜',
'fingers crossed':'🔜',
'signal strength':'📶',
'office building':'🏢',
'congratulations':'👏🎉',
'american dollar':'💵',
'black telephone':'☎',
'ten pin bowling':'🎳',
'bridge at night':'🌉',
'school crossing':'🚸',
'izakaya lantern':'🏮',
'closed umbrella':'🌂',
'quivering mouth':'😖',
'shopping center':'🏬',
'circle and star':'💫',
'with open mouth':'😮',
'izakaya lantern':'🏮',
'fire department':'🚒',
'mcdonalds fries':'🍟',
'performing arts':'🎭',
'japanese goblin':'👺',
'izakaya lantern':'🏮',
'japanese castle':'🏯',
'japanese goblin':'👺',
'tropical island':'🌴',
'splashing sweat':'💦',
'splashing water':'💦',
'partially sunny':'⛅',
'thought balloon':'💭',
'valentine’s day':'💘',
'throwing a kiss':'😘',
'wrapped present':'🎁',
'winter olympics':'🎿',
'knee high boots':'👢',
'womens restroom':'🚺',
'leaves falling':'🍃',
'multiplication':'✖',
'climate change':'🌏🔄',
'aerial tramway':'🚡',
'reception bars':'📶',
'bottle feeding':'🍼',
'global warming':'🌏🔥',
'bactrian camel':'🐫',
'two bump camel':'🐫',
'person on bike':'🚴',
'pointing right':'➡',
'tetraodontidae':'🐡',
'breaking heart':'💔',
'digital camera':'📷',
'carousel horse':'🎠',
'merry-go-round':'🎠',
'chequered flag':'🏁',
'checkered flag':'🏁',
'cherry blossom':'🌸',
'fork and knife':'🍴',
'knife and fork':'🍴',
'cocktail glass':'🍸',
'cocktail glass':'🍸',
'fortune teller':'🔮',
'delivery truck':'🚚',
'no pedestrians':'🚷',
'expressionless':'😑',
'blowing a kiss':'😘',
'jack-o-lantern':'🎃',
'water fountain':'⛲',
'world wide web':'🌐',
'multiple heart':'💗',
'blowing kisses':'😘',
'jack-o-lantern':'🎃',
'cherry blossom':'🌸',
'lightning bolt':'⚡',
'happy birthday':'🎉🎂🎈🎉',
'emergency room':'🏥',
'carousel horse':'🎠',
'japanese dolls':'🎎',
'imperial dolls':'🎎',
'japanese dress':'👘',
'border control':'🛂',
'soft ice cream':'🍦',
'deciduous tree':'🌳',
'identification':'🆔',
'train platform':'🚉',
'tropical drink':'🍹',
'slice of pizza':'🍕',
'blood donation':'💉',
'thought bubble':'💭',
'cherry blossom':'🌸',
'lesbian couple':'👭',
'evergreen tree':'🌲',
'kentucky derby':'👒',
'American Samoa':'🇦🇸',
'Cayman Islands':'🇰🇾',
'Czech Republic':'🇨🇿',
'United Kingdom':'🇬🇧',
'New Caledonian':'🇳🇨',
'South Sudanese':'🇸🇸',
'Faroe Islands':'🇫🇴',
'French Guiana':'🇬🇫',
'Great Britain':'🇬🇧',
'Guinea-Bissau':'🇬🇼',
'Liechtenstein':'🇱🇮',
'New Caledonia':'🇳🇨',
'New Zealander':'🇳🇿',
'Saudi Arabian':'🇸🇦',
'South African':'🇿🇦',
'alien monster':'👾',
'space invader':'👾',
'anticlockwise':'🔄',
'athletic shoe':'👟',
'australia day':'🐨',
'chinese camel':'🐫',
'baggage claim':'🛄',
'colored lines':'📊',
'phone battery':'🔋',
'beating heart':'💓',
'notifications':'🔔',
'birthday list':'🎂',
'birthday cake':'🎂',
'left triangle':'◀',
'question mark':'❓',
'bookmark tabs':'📑',
'loaf of bread':'🍞',
'brokenhearted':'💔',
'carp streamer':'🎏',
'kids crossing':'🚸',
'musical notes':'🎶',
'cinco de mayo':'💃',
'clapper board':'🎬',
'pink umbrella':'🌂',
'martini glass':'🍸',
'confetti ball':'🎊',
'roadwork sign':'🚧',
'space shuttle':'🚀',
'24-hour store':'🏪',
'loving couple':'💑',
'crescent moon':'🌙',
'crossed flags':'🎌',
'eyebrow sweat':'😥',
'shooting star':'🌠',
'surgical mask':'😷',
'hands on head':'🙆',
'san francisco':'🌁',
'water feature':'⛲',
'international':'🌐',
'jealous heart':'💚',
'foot in mouth':'😬',
'growing heart':'💗',
'division sign':'➗',
'traffic light':'🚥',
'hot chocolate':'☕',
'accommodation':'🏨',
'asian lantern':'🏮',
'dressing gown':'👘',
'holding hands':'👫',
'male restroom':'🚹',
'speak-no-evil':'🙊',
'speak no evil':'🙊',
'speech bubble':'💬',
'train station':'🚉',
'womans sandal':'👡',
'yellow flower':'🌻',
'tanabata tree':'🎋',
'beating heart':'💓',
'growing heart':'💗',
'traffic light':'🚦',
'videocassette':'📼',
'dancing girls':'👯',
'cowgirl boots':'👢',
'high voltage':'⚡',
'medical mask':'😷',
'fried shrimp':'🍤',
'left luggage':'🛅',
'wedding bell':'🔔',
'magic 8 ball':'🎱',
'party popper':'🎉',
'fast forward':'⏩',
'fountain pen':'✒',
'rotary phone':'☎',
'yellow heart':'💛',
'purple heart':'💜',
'bowling ball':'🎳',
'broken heart':'💔',
'heart broken':'💔',
'ferris wheel':'🎡',
'domestic cat':'🐈',
'santa clause':'🎅',
'christianity':'⛪',
'musical note':'🎵',
'lock and key':'🔐',
'construction':'🚧',
'mobile phone':'📱',
'crystal ball':'🔮',
'disappointed':'😞',
'blowing kiss':'😘',
'medical mask':'😷',
'hot beverage':'☕',
'father’s day':'👨',
'flag in hole':'⛳',
'ferris wheel':'🎡',
'flag in hole':'⛳',
'sweet potato':'🍠',
'french fries':'🍟',
'fried shrimp':'🍤',
'triple heart':'💗',
'crystal ball':'🔮',
'cheeseburger':'🍔',
'hear no evil':'🙉',
'bullet train':'🚅',
'horse racing':'🏇',
'ferris wheel':'🎡',
'skinny jeans':'👖',
'skeleton key':'🔑',
'kissing lips':'💋',
'people-mover':'🚐',
'tears of joy':'😂',
'troublemaker':'😈',
'snowboarding':'🏂',
'strawberries':'🍓',
'spiral shell':'🐚',
'thanksgiving':'🍴',
'harry potter':'✨⚡👓🏰',
'bengal tiger':'🐅',
'eiffel tower':'🗼',
'ear of maize':'🌽',
'small hearts':'💕',
'dissatisfied':'😒',
'purple heart':'💜',
'yellow heart':'💛',
'video camera':'📹',
"women's boots":'👢',
'yellow heart':'💛',
'Burkina Faso':'🇧🇫',
'Cook Islands':'🇨🇰',
'North Korean':'🇰🇵',
'South Korean':'🇰🇷',
'Puerto Rican':'🇵🇷',
'Saudi Arabia':'🇸🇦',
'Sierra Leone':'🇸🇱',
'South Africa':'🇿🇦',
'Afghanistan':'🇦🇫',
'Argentinian':'🇦🇷',
'Azerbaijani':'🇦🇿',
'Bangladeshi':'🇧🇩',
'Cameroonian':'🇨🇲',
'Costa Rican':'🇨🇷',
'El Salvador':'🇸🇻',
'Salvadorian':'🇸🇻',
'Ivory Coast':'🇨🇮',
'Mauritanian':'🇲🇷',
'Montenegran':'🇲🇪',
'Netherlands':'🇳🇱',
'New Zealand':'🇳🇿',
'North Korea':'🇰🇵',
'South Korea':'🇰🇷',
'Palestinian':'🇵🇸',
'Philippines':'🇵🇭',
'Puerto Rico':'🇵🇷',
'South Sudan':'🇸🇸',
'Switzerland':'🇨🇭',
'golden hour':'🌆',
'alarm clock':'⏰',
'fire engine':'🚒',
'sagittarius':'♐',
'curved down':'⤵',
'baby bottle':'🍼',
'yellow bird':'🐤',
'baby change':'🚼',
'asian camel':'🐫',
'red balloon':'🎈',
'bank branch':'🏦',
'dollar bill':'💵',
'communities':'👥',
'hairdresser':'💈',
'heart alarm':'💓',
'play button':'▶',
'closed book':'📕',
'orange book':'📙',
'green heart':'💚',
'white bread':'🍞',
'caterpillar':'🐛',
'silhouettes':'👤',
'racing flag':'🏁',
'pink flower':'🌸',
'circus tent':'🎪',
'corner shop':'🏪',
'kwik-e-mart':'🏪',
'credit card':'💳',
'diners club':'💳',
'clairvoyant':'🔮',
'indian food':'🍛',
'spiral eyes':'😵',
'comet trail':'💫',
'post office':'🏤',
'blow a kiss':'😘',
'blow kisses':'😘',
'happy tears':'😂',
'fallen leaf':'🍂',
'hole in one':'⛳',
'fax machine':'📠',
'fire engine':'🚒',
'floppy disk':'💾',
'embarrassed':'😳',
'green apple':'🍏',
'petrol pump':'⛽',
'green apple':'🍏',
'closed book':'📕',
'orange book':'📙',
'green heart':'💚',
'hairdresser':'💇',
'green heart':'💚',
'see no evil':'🙈',
'thunderbolt':'⚡',
'alarm clock':'⏰',
'waxing moon':'🌒',
'waning moon':'🌘',
'red lantern':'🏮',
'hinamatsuri':'🎎',
'lady beetle':'🐞',
'yellow book':'📒',
'railway car':'🚃',
'love letter':'💌',
'mens toilet':'🚹',
'underground':'🚇',
'green apple':'🍏',
'lead pencil':'✏',
'snowboarder':'🏂',
'water drops':'💦',
'green heart':'💚',
'steam train':'🚂',
'vaccination':'💉',
'fallen leaf':'🍂',
'poultry leg':'🍗',
'thumbs down':'👎',
'ticket stub':'🎫',
'tokyo tower':'🗼',
'formal wear':'🎩',
'fruit punch':'🍹',
'unimpressed':'😒',
'love letter':'💌',
'green heart':'💚',
'playstation':'🎮',
'pointing up':'👆',
'snowboarder':'🏂',
'snowboarder':'🏂',
'postal horn':'📯',
'soccer ball':'⚽',
'water wave':'🌊',
'astonished':'😲',
'automobile':'🚗',
'baby chick':'🐤',
'basketball':'🏀',
'aa battery':'🔋',
'bike party':'🚴🎉',
'pufferfish':'🐡',
'green book':'📗',
'blue heart':'💙',
'school bus':'🚌',
'space ship':'🚀',
'silhouette':'👤',
'maple leaf':'🍁',
'index card':'📇',
'fairground':'🎠',
'wind socks':'🎏',
'gua pi mao':'👲',
'baby angel':'👼',
'film slate':'🎬',
'confounded':'😖',
'nonplussed':'😕',
'frying pan':'🍳',
'registered':'®',
'trade mark':'™',
'mastercard':'💳',
'smartphone':'📱',
'businesses':'🏢',
'crying cat':'😿',
'direct hit':'🎯',
'cross eyes':'😵',
'water drop':'💧',
'hallelujah':'🙌',
'light bulb':'💡',
'flashlight':'🔦',
'eyeglasses':'👓',
'home alone':'😱',
'cold sweat':'😓',
'frustrated':'😤',
'open mouth':'😮',
'tongue out':'😝',
'tongue out':'😛',
'industrial':'🏭',
'fairground':'🎡',
'fire truck':'🚒',
'narutomaki':'🍥',
'pink swirl':'🍥',
'watermelon':'🍉',
'strawberry':'🍓',
'footprints':'👣',
'university':'🎓',
'graduation':'🎓',
'green book':'📗',
'frustrated':'😁',
'headphones':'🎧',
'two hearts':'💕',
'lovestruck':'💘',
'check mark':'✔',
'minus sign':'➖',
'helicopter':'🚁',
'brightness':'🔆',
'high heels':'👠',
'shinkansen':'🚅',
'light rail':'🚈',
'bumble bee':'🐝',
'horse race':'🏇',
'hair flick':'💁',
'koala bear':'🐨',
'australian':'🐨',
'light rail':'🚈',
'trolleybus':'🚎',
'hold hands':'👫',
'cantaloupe':'🍈',
'memorandum':'📝',
'microphone':'🎤',
'microscope':'🔬',
'debit card':'💳',
'paw prints':'🐾',
'pedestrian':'🚶',
'sunglasses':'😎',
'soft serve':'🍦',
'strawberry':'🍓',
'television':'📺',
'blood test':'💉',
'polo shirt':'👕',
'stargazing':'🔭',
'television':'📺',
'tongue out':'👅',
'two hearts':'💕',
'gay couple':'👬',
'not amused':'😒',
'two hearts':'💕',
'love hotel':'🏩',
'blue heart':'💙',
'peace sign':'✌',
'air quotes':'✌',
'video game':'🎮',
'excellence':'👌',
'video tape':'📼',
'wristwatch':'⌚',
'ocean wave':'🌊',
'watermelon':'🍉',
'strawberry':'🍓',
'distraught':'😫',
'wind chime':'🎐',
'bunny ears':'👯',
'gold heart':'💛',
'Australian':'🇦🇺',
'Azerbaijan':'🇦🇿',
'Bahamanian':'🇧🇸',
'Bangladesh':'🇧🇩',
'Belarusian':'🇧🇾',
'Bulgarian ':'🇧🇬',
'Cape Verde':'🇨🇻',
'Costa Rica':'🇨🇷',
'Ecuadorian':'🇪🇨',
'Union Jack':'🇬🇧',
'Guadeloupe':'🇬🇵',
'Indonesian':'🇮🇩',
'Kazakhstan':'🇰🇿',
'Kyrgyzstan':'🇰🇬',
'Lithuanian':'🇱🇹',
'Luxembourg':'🇱🇺',
'Macedonian':'🇲🇰',
'Madagascar':'🇲🇬',
'Martinique':'🇲🇶',
'Mauritania':'🇲🇷',
'Montenegro':'🇲🇪',
'Montserrat':'🇲🇸',
'Mozambique':'🇲🇿',
'Nicaraguan':'🇳🇮',
'Panamanian':'🇵🇦',
'Paraguayan':'🇵🇾',
'Portuguese':'🇵🇹',
'Madagascar':'🇲🇬',
'San Marino':'🇸🇲',
'Senegalese':'🇸🇳',
'Seychelles':'🇸🇨',
'Sri Lankan':'🇱🇰',
'Anguillan':'🇦🇮',
'Argentina':'🇦🇷',
'Australia':'🇦🇺',
'Barbadian':'🇧🇧',
'Botswanan':'🇧🇼',
'Brazilian':'🇧🇷',
'Burkinabe':'🇧🇫',
'Cambodian':'🇰🇭',
'Colombian':'🇨🇴',
'Curaçaoan':'🇨🇼',
'Congolese':'🇨🇩',
'Dominican':'🇩🇴',
'Ethiopian':'🇪🇹',
'Gibraltar':'🇬🇮',
'Guatemala':'🇬🇹',
'Hong Kong':'🇭🇰',
'Hungarian':'🇭🇺',
'Icelandic':'🇮🇸',
'Indonesia':'🇮🇩',
'Jordanian':'🇯🇴',
'Lithuania':'🇱🇹',
'Macedonia':'🇲🇰',
'Malaysian':'🇲🇾',
'Mongolian':'🇲🇳',
'Nicaragua':'🇳🇮',
'Norwegian':'🇳🇴',
'Pakistani':'🇵🇰',
'Palestine':'🇵🇸',
'Mauritius':'🇲🇺',
'Singapore':'🇸🇬',
'Slovakian':'🇸🇰',
'Slovenian':'🇸🇮',
'Sri Lanka':'🇱🇰',
'Swaziland':'🇸🇿',
'Red Cross':'🇨🇭',
'megaphone':'📣',
'cable car':'🚡',
'aeroplane':'✈',
'ambulance':'🚑',
'watch out':'🚨',
'revolving':'🔄',
'superbowl':'🏈',
'fisherman':'⚓',
'anguished':'😧',
'black ant':'🐜',
'reception':'📶',
'capricorn':'♑',
'community':'👥',
'bar chart':'📊',
'heartbeat':'💓',
'lunch box':'🍱',
'bicyclist':'🚴',
'billiards':'🎱',
'shortcake':'🍰',
'celebrate':'🎉',
'telephone':'☎',
'blue book':'📘',
'open book':'📖',
'collision':'💥',
'price tag':'🔖',
'briefcase':'💼',
'centipede':'🐛',
'wild west':'🌵',
'world day':'📅',
'fireworks':'🎆',
'capricorn':'♑',
'koinobori':'🎏',
'fish flag':'🎏',
'megaphone':'📣',
'money bag':'💰',
'fireworks':'🎆',
'chocolate':'🍫',
'christmas':'🎄',
'cellphone':'📱',
'snowflake':'❄',
'christian':'⛪',
'creatives':'🎨',
'clapboard':'🎬',
'golf clap':'👏',
'scrunched':'😖',
'7-eleven®':'🏪',
'fried egg':'🍳',
'breakfast':'🍳',
'copyright':'©',
'visa card':'💳',
'full moon':'🌕',
'crocodile':'🐊',
'alligator':'🐊',
'two flags':'🎌',
'littering':'🚯',
'voicemail':'➿',
'listening':'👂',
'excellent':'👌',
'hell yeah':'🙌',
'thank you':'🙏',
'lightbulb':'💡',
'wide eyed':'👀',
'massaging':'💆',
'screaming':'😱',
'hard work':'😓',
'ballerina':'🙆',
'concerned':'😰',
'mouthless':'😶',
'pollution':'🏭',
'tangerine':'🍊',
'coachella':'🎡',
'fireworks':'🎆',
'explosion':'🎆',
'fist bump':'👊',
'3.5″ disk':'💾',
'hamburger':'🍔',
'tangerine':'🍊',
'pointless':'🙅▶',
'pineapple':'🍍',
'footsteps':'👣',
'fuel pump':'⛽',
'halloween':'👻',
'blue book':'📘',
'open book':'📖',
'grimacing':'😬',
'happy cat':'😸',
'guardsman':'💂',
'halloween':'🎃',
'full moon':'🌕',
'hamburger':'🍔',
'headphone':'🎧',
'ambulance':'🚑',
'sunflower':'🌻',
'lightning':'⚡',
'honey pot':'🍯',
'red cross':'🏥',
'hourglass':'⌛',
'surprised':'😯',
'ice cream':'🍨',
'fireworks':'🎆',
'concierge':'💁',
'halloween':'🎃',
'kiss mark':'💋',
'whistling':'😙',
'australia':'🐨',
'fireworks':'🎆',
'magnifier':'🔍',
'backwards':'⬅',
'backpacks':'🎒',
'hyperlink':'🔗',
'love note':'💌',
'moustache':'👨',
'milky way':'🌌',
'night sky':'🌌',
'documents':'📃',
'palm tree':'🌴',
'paperclip':'📎',
'sorrowful':'😔',
'cigarette':'🚬',
'snowboard':'🏂',
'snowflake':'❄',
'mr whippy':'🍦',
'southeast':'↘',
'southwest':'↙',
'spaghetti':'🍝',
'speedboat':'🚤',
'motorboat':'🚤',
'powerboat':'🚤',
'emergency':'🆘',
'paperclip':'📎',
'palm tree':'🌴',
'sunflower':'🌻',
'sunflower':'🌻',
'superbowl':'🏈',
'freestyle':'🏊',
'tee shirt':'👕',
'wish tree':'🎋',
'tangerine':'🍊',
'green tea':'🍵',
'telephone':'📞',
'telescope':'🔭',
'thumbs up':'👍',
'exhausted':'😫',
'red tower':'🗼',
'red apple':'🍎',
'trademark':'™',
'flagstick':'🚩',
'sunflower':'🌻',
'kiss mark':'💋',
'camcorder':'📹',
'star wars':'🚀🌕💥',
'timepiece':'⌚',
'pineapple':'🍍',
'money bag':'💰',
'wind bell':'🎐',
'jellyfish':'🎐',
'education':'🏫',
'snowflake':'❄',
'tap dance':'👯',
'showgirls':'👯',
'world cup':'⚽',
'blast off':'🚀',
'eggplant':'🍆',
'backpack':'🎒',
'airplane':'✈',
'hospital':'🏥',
'look out':'🚨',
'football':'🏈',
'gridiron':'🏈',
'animated':'👋',
'aquarius':'♒',
'scorpius':'♏',
'aquarius':'♒',
'painting':'🎨',
'airplane':'✈',
'plantain':'🍌',
'baseball':'⚾',
'softball':'⚾',
'swimsuit':'👙',
'churches':'⛪',
'cue ball':'🎱',
'birthday':'🎂',
'business':'🏢',
'scissors':'✂',
'blowfish':'🐡',
'together':'👭',
'toadfish':'🐡',
'notebook':'📓',
'bookmark':'🔖',
'bookmark':'🔖',
'skittles':'🎳',
'marriage':'👰',
'suitcase':'💼',
'bus stop':'🚏',
'calendar':'📅',
'carnival':'🎠',
'housecat':'🐈',
'cherries':'🍒',
'facebook':'😃📘',
'chestnut':'🌰',
'chickens':'🐔',
'confetti':'🎊',
'director':'🎬',
'applause':'👏',
'clapping':'👏',
'envelope':'✉',
'overcast':'☁',
'cocktail':'🍸',
'confetti':'🎊',
'confused':'😕',
'roadwork':'🚧',
'hard-hat':'👷',
'new moon':'🌑',
'feminism':'👩🏾👍',
'bullseye':'🎯',
'seaworld':'🐬🌏',
'sparkles':'✨',
'elephant':'🐘',
'envelope':'✉',
'eyesight':'👀',
'eyeballs':'👀',
'steaming':'😤',
'bird flu':'😷',
'laughing':'😂',
'industry':'🏭',
'chestnut':'🌰',
'sailboat':'⛵',
'festivus':'💪',
'sparkler':'🎇',
'firework':'🎆',
'fishcake':'🍥',
'bro fist':'👊',
'blushing':'😳',
'eggplant':'🍆',
'cherries':'🍒',
'fountain':'⛲',
'shamrock':'🍀',
'gas pump':'⛽',
'gasoline':'⛽',
'gemstone':'💎',
'glossary':'📖',
'graduate':'🎓',
'notebook':'📓',
'bookmark':'🔖',
'freezing':'😁',
'grinning':'😀',
'handyman':'🔨',
'hanukkah':'🔯',
'hatching':'🐣',
'earphone':'🎧',
'gift box':'💝',
'airplane':'✈',
'hospital':'🏥',
'hibiscus':'🌺',
'stiletto':'👠',
'monorail':'🚝',
'butchers':'🔪',
'honeybee':'🐝',
'hospital':'🏥',
'surprise':'😯',
'whatever':'💁',
'fortress':'🏯',
'red mask':'👺',
'trousers':'👖',
'lady bug':'🐞',
'lemonade':'🍋',
'tram car':'🚋',
'creative':'🎨',
'lipstick':'💄',
'lollipop':'🍭',
'canadian':'🍁',
'honeydew':'🍈',
'universe':'🌌',
'disaster':'🆘',
'minidisc':'💽',
'document':'📃',
'reaching':'🙋',
'grinning':'😀',
'innocent':'😇',
'grinning':'😃',
'smirking':'😏',
'flirting':'😏',
'football':'⚽',
'sparkles':'✨',
'midnight':'🕛',
'internet':'🌐',
'seashell':'🐚',
'seedling':'🌱',
'trophies':'🏆',
'violence':'💥',
'distress':'🆘',
'level up':'🆙',
'beer mug':'🍺',
'clashing':'💥',
'new york':'🗽',
'sun with':'🌞',
'yosemite':'🌄',
'monorail':'🚝',
'swimming':'🏊',
'tanabata':'🎋',
'mandarin':'🍊',
'campsite':'⛺',
'families':'👪',
'thinking':'💭',
'restroom':'🚽',
'strength':'💪',
'bathroom':'🚽',
'red flag':'🚩',
'election':'☑',
'geometry':'📐',
'hibiscus':'🌺',
'tortoise':'🐢',
'lesbians':'👭',
'umbrella':'☔',
'unamused':'😒',
'wildlife':'🐅',
'balloons':'🎈',
'lipstick':'💄',
'marriage':'💒',
'pointing':'👉',
'students':'🎒',
'calendar':'📅',
'gift box':'🎁',
'Albanian':'🇦🇱',
'Algerian':'🇩🇿',
'Andorran':'🇦🇩',
'Anguilla':'🇦🇮',
'Armenian':'🇦🇲',
'Austrian':'🇦🇹',
'Bahraini':'🇧🇭',
'Barbados':'🇧🇧',
'Bolivian':'🇧🇴',
'Botswana':'🇧🇼',
'Bruneian':'🇧🇳',
'Bulgaria':'🇧🇬',
'Cambodia':'🇰🇭',
'Cameroon':'🇨🇲',
'Canadian':'🇨🇦',
'Chileans':'🇨🇱',
'Colombia':'🇨🇴',
'Croatian':'🇭🇷',
'Djibouti':'🇩🇯',
'Dominica':'🇩🇲',
'Egyptian':'🇪🇬',
'Eritrean':'🇪🇷',
'Estonian':'🇪🇪',
'Ethiopia':'🇪🇹',
'Gabonese':'🇬🇦',
'Georgian':'🇬🇪',
'Ghanaian':'🇬🇭',
'Honduras':'🇭🇳',
'Jamaican':'🇯🇲',
'Japanese':'🇯🇵',
'Kiribati':'🇰🇮',
'Lebanese':'🇱🇧',
'Liberian':'🇱🇷',
'American':'🇺🇸',
'Malaysia':'🇲🇾',
'Maldives':'🇲🇻',
'Moldovan':'🇲🇩',
'Mongolia':'🇲🇳',
'Moroccan':'🇲🇦',
'Namibian':'🇳🇦',
'Nepalese':'🇳🇵',
'Nigerien':'🇳🇪',
'Nigerian':'🇳🇬',
'Pakistan':'🇵🇰',
'Paraguay':'🇵🇾',
'Peruvian':'🇵🇪',
'Filipino':'🇵🇭',
'Portugal':'🇵🇹',
'Romanian':'🇷🇴',
'Slovakia':'🇸🇰',
'Slovenia':'🇸🇮',
'Somalian':'🇸🇴',
'Sudanese':'🇸🇩',
'Suriname':'🇸🇷',
'Emirates':'🇦🇪',
'Albania':'🇦🇱',
'Algeria':'🇩🇿',
'Andorra':'🇦🇩',
'Armenia':'🇦🇲',
'Austria':'🇦🇹',
'Bahamas':'🇧🇸',
'Bahrain':'🇧🇭',
'Bengali':'🇧🇩',
'Belarus':'🇧🇾',
'Belgium':'🇧🇪',
'Belgian':'🇧🇪',
'Bermuda':'🇧🇲',
'Bolivia':'🇧🇴',
'Burundi':'🇧🇮',
'Chinese':'🇨🇳',
'Comoros':'🇰🇲',
'Comoran':'🇰🇲',
'Croatia':'🇭🇷',
'Curaçao':'🇨🇼',
'Cypriot':'🇨🇾',
'Denmark':'🇩🇰',
'Ecuador':'🇪🇨',
'Eritrea':'🇪🇷',
'Estonia':'🇪🇪',
'Finland':'🇫🇮',
'Finnish':'🇫🇮',
'Gambian':'🇬🇲',
'Georgia':'🇬🇪',
'Germany':'🇩🇪',
'British':'🇬🇧',
'UK Flag':'🇬🇧',
'Grenada':'🇬🇩',
'Hungary':'🇭🇺',
'Iceland':'🇮🇸',
'Iranian':'🇮🇷',
'Ireland':'🇮🇪',
'Israeli':'🇮🇱',
'Italian':'🇮🇹',
'Jamaica':'🇯🇲',
'Kuwaiti':'🇰🇼',
'Latvian':'🇱🇻',
'Lebanon':'🇱🇧',
'Lesotho':'🇱🇸',
'Liberia':'🇱🇷',
'Mexican':'🇲🇽',
'Moldova':'🇲🇩',
'Morocco':'🇲🇦',
'Myanmar':'🇲🇲',
'Burmese':'🇲🇲',
'Namibia':'🇳🇦',
'Nigeria':'🇳🇬',
'Palauan':'🇵🇼',
'Spanish':'🇪🇸',
'Réunion':'🇷🇪',
'Romania':'🇷🇴',
'Russian':'🇷🇺',
'Rwandan':'🇷🇼',
'Senegal':'🇸🇳',
'Serbian':'🇷🇸',
'Somalia':'🇸🇴',
'Swedish':'🇸🇪',
'Turkish':'🇹🇷',
'Emirati':'🇦🇪',
'Vietnam':'🇻🇳',
'gondola':'🚠',
'ropeway':'🚡',
'gondola':'🚡',
'bullant':'🐜',
'refresh':'🔄',
'reverse':'🔄',
'revolve':'🔄',
'upwards':'⬆',
'palette':'🎨',
'clashes':'💥',
'shocked':'😲',
'gasping':'😲',
'sneaker':'👟',
'trainer':'👟',
'assault':'💥',
'animals':'🐅',
'nursery':'🚼',
'toddler':'👶',
'customs':'🛃',
'bananas':'🍌',
'bathing':'🛀',
'bathtub':'🛁',
'battery':'🔋',
'bicycle':'🚲',
'bicycle':'🚴',
'cyclist':'🚴',
'cycling':'🚴',
'bathers':'👙',
'snooker':'🎱',
'balloon':'🎈',
'present':'🎁',
'pen nib':'✒',
'scissor':'✂',
'cutting':'✂',
'blossom':'🌼',
'bouquet':'💐',
'flowers':'💐',
'bowling':'🎳',
'married':'👰',
'wedding':'👰',
'july 17':'📅',
'rolodex':'📇',
'chicken':'🐔',
'snowman':'⛄',
'present':'🎁',
'glowing':'🌟',
'balloon':'🎈',
'burrito':'🌯',
'big top':'🎪',
'mailbox':'📪',
'postbox':'📮',
'martini':'🍸',
'explode':'💥',
'puzzled':'😕',
'builder':'👷',
'biscuit':'🍪',
'cooking':'🍳',
'efforts':'💪',
'sad cat':'😿',
'psychic':'🔮',
'dessert':'🍮',
'student':'🎒',
'pudding':'🍮',
'customs':'🛃',
'dancing':'💃',
'package':'📦',
'archery':'🎯',
'worried':'😥',
'dolphin':'🐬',
'doorway':'🚪',
'rowboat':'🚣',
'droplet':'💧',
'farming':'🌾',
'hearing':'👂',
'praying':'🙏',
'turrets':'🏰',
'glasses':'👓',
'massage':'💆',
'kissing':'😘',
'no deal':'🙅',
'nervous':'😰',
'silence':'😶',
'factory':'🏭',
'top hat':'🎩',
'necktie':'👔',
'in love':'💖',
'fearful':'😨',
'fishing':'🎣',
'flexing':'💪',
'reaches':'🙋',
'flushed':'😳',
'cutlery':'🍴',
'ireland':'🍀',
'seafood':'🍤',
'diamond':'💎',
'college':'🎓',
'bouquet':'💐',
'grimace':'😬',
'nervous':'😬',
'awkward':'😬',
'haircut':'💇',
'fearful':'😨',
'hamster':'🐹',
'handbag':'👜',
'earbuds':'🎧',
'bouquet':'💐',
'medical':'🏥',
'suburbs':'🏡',
'dessert':'🍨',
'bellhop':'💁',
'lantern':'🏮',
'pumpkin':'🎃',
'monster':'👹',
'whistle':'😙',
'ladybug':'🐞',
'mystery':'🔍',
'between':'↔',
'station':'🚉',
'padlock':'🔒',
'bawling':'😭',
'sobbing':'😭',
'mahjong':'🀄',
'caveman':'🍖',
'singing':'🎤',
'running':'🏃',
'karaoke':'🎤',
'magnify':'🔬',
'science':'🔬',
'minibus':'🚐',
'minivan':'🚐',
'package':'📦',
'walking':'🚶',
'penguin':'🐧',
'pensive':'😔',
'helping':'👋',
'smiling':'😃',
'nervous':'😅',
'angelic':'😇',
'content':'😊',
'sunnies':'😎',
'snowing':'❄',
'snowman':'⛄',
'sparkle':'✨',
'iwazaru':'🙊',
'speaker':'🔈',
'apparel':'👚',
'rainbow':'🌈',
'blossom':'🌼',
'station':'🚉',
'written':'📝',
'noodles':'🍜',
'pushpin':'📌',
't-shirt':'👕',
'swimmer':'🏊',
'morning':'🌄',
'sunrise':'🌅',
'surfing':'🏄',
'seafood':'🍣',
'sashimi':'🍣',
'swimmer':'🏊',
'syringe':'💉',
'turtles':'🐢',
't-shirt':'👕',
'taxicab':'🚕',
'july 17':'📆',
'handset':'📞',
'camping':'⛺',
'chicken':'🐔',
'top hat':'🎩',
'tractor':'🚜',
'farming':'🚜',
'trumpet':'🎺',
'bouquet':'💐',
'gay men':'👬',
'raining':'☔',
'bouquet':'💐',
'victory':'✌',
'volcano':'🌋',
'buffalo':'🐃',
'goodbye':'👋',
'wailing':'😫',
'top hat':'🎩',
'wedding':'💒',
'bouquet':'💐',
'wedding':'💒',
'alcohol':'🍷',
'winking':'😉',
'reading':'📖',
'sandals':'👡',
'ribbons':'🎀',
'worried':'😟',
'sadface':'😟',
'couples':'💑',
'spanner':'🔧',
'ticket':'🎫',
'anchor':'⚓',
'flight':'✈',
'global':'🌏',
'flying':'✈',
'anchor':'⚓',
'iphone':'📱',
'grumpy':'😠',
'pained':'😧',
'stairs':'📶',
'taurus':'♉',
'expand':'↔',
'gemini':'♊',
'double':'2⃣',
'cancer':'♋',
'pisces':'♓',
'artist':'🎨',
'runner':'👟',
'cherub':'👼',
'banana':'🍌',
'barber':'💈',
'shoewr':'🛀',
'ringer':'🔔',
'bikini':'👙',
'8 ball':'🎱',
'rewind':'⏪',
'flower':'🌼',
'ledger':'📒',
'pistol':'🔫',
'bridge':'🌉',
'cactus':'🌵',
'desert':'🌵',
'camera':'📷',
'kitten':'🐱',
'feline':'🐈',
'cherry':'🍒',
'sakura':'🌸',
'effort':'💪',
'dragon':'🐉',
'dragon':'🐲',
'dancer':'💃',
'guitar':'🎸',
'cactus':'🌵',
'cinema':'🎦',
'movies':'🎦',
'circus':'🎪',
'cheers':'🍻',
'locked':'🔐',
'cloudy':'☁',
'impact':'💥',
'cookie':'🍪',
'animal':'🐅',
'office':'🏢',
'couple':'💑',
'crying':'😢',
'crying':'😢',
'dancer':'💃',
'litter':'🚯',
'dragon':'🐉',
'dragon':'🐲',
'dinner':'🍴',
'e-mail':'📧',
'planet':'🌏',
'easter':'🐰',
'rabbit':'🐇',
'rabbit':'🐰',
'church':'⛪',
'letter':'✉',
'castle':'🏰',
'seeing':'👀',
'scream':'😱',
'doctor':'😷',
'x arms':'🙅',
'eating':'😮',
'cheeky':'😛',
'tongue':'😛',
'silent':'😶',
'autumn':'🍂',
'hammer':'🔨',
'wrench':'🔧',
'deaths':'💀',
'scared':'😨',
'folder':'📁',
'strong':'💪',
'muscle':'💪',
'chicks':'🐤',
'flexed':'💪',
'tomato':'🍅',
'grapes':'🍇',
'banana':'🍌',
'prayer':'🙏',
'clover':'🍀',
'shrimp':'🍤',
'kermit':'🐸',
'scroll':'📜',
'ledger':'📒',
'smiley':'😀',
'guitar':'🎸',
'pistol':'🔫',
'burger':'🍔',
'hammer':'🔨',
'jewish':'🔯',
'bright':'🔆',
'jockey':'🏇',
'coffee':'☕',
'suburb':'🏡',
'hushed':'😯',
'goblin':'👿',
'family':'👪',
'kimono':'👘',
'pistol':'🔫',
'leaves':'🍃',
'spring':'🍃',
'ledger':'📒',
'binder':'📒',
'search':'🔍',
'makeup':'💄',
'crying':'😭',
'couple':'👫',
'turban':'👳',
'rocket':'🚀',
'canada':'🍁',
'writes':'📝',
'subway':'🚇',
'galaxy':'🌌',
'outbox':'📤',
'parcel':'📦',
'beeper':'📟',
'clippy':'📎',
'walker':'🚶',
'pencil':'✏',
'smiley':'😃',
'sexual':'😏',
'soccer':'⚽',
'volume':'🔈',
'speech':'💬',
'spring':'🌱',
'pencil':'✏',
'school':'🏫',
'waxing':'🌔',
'waning':'🌖',
'voting':'☑',
'summer':'🌞',
'surfer':'🏄',
'bikini':'👙',
'helped':'👋',
'cloudy':'⛅',
'flower':'🌻',
'sunset':'🌅',
'surfer':'🏄',
'needle':'💉',
'orange':'🍊',
'matcha':'🍵',
'tennis':'🎾',
'ticket':'🎫',
'fed up':'😫',
'toilet':'🚽',
'people':'👥',
'tomato':'🍅',
'tongue':'👅',
'trophy':'🏆',
'trains':'🚆',
'turtle':'🐢',
'ribbon':'🎀',
'violin':'🎻',
'violins':'🎻',
'waving':'👋',
'skiing':'🎿',
'trophy':'🏆',
'winter':'⛄',
'ballet':'👯',
'female':'👩',
'blouse':'👚',
'change':'🔄',
'speech':'😮💬',
'trophy':'🏆',
'wrench':'🔧',
'chance':'🎲',
'Afghan':'🇦🇫',
'Aussie':'🇦🇺',
'Belize':'🇧🇿',
'Bhutan':'🇧🇹',
'Brazil':'🇧🇷',
'Brunei':'🇧🇳',
'Canada':'🇨🇦',
'Cyprus':'🇨🇾',
'Danish':'🇩🇰',
'Fijian':'🇫🇯',
'France':'🇫🇷',
'French':'🇫🇷',
'Gambia':'🇬🇲',
'German':'🇩🇪',
'Greece':'🇬🇷',
'Guinea':'🇬🇳',
'Guyana':'🇬🇾',
'Indian':'🇮🇳',
'Israel':'🇮🇱',
'Jordan':'🇯🇴',
'Kenyan':'🇰🇪',
'Kuwait':'🇰🇼',
'Kyrgyz':'🇰🇬',
'Latvia':'🇱🇻',
'U.S.A.':'🇺🇸',
'Libyan':'🇱🇾',
'Malawi':'🇲🇼',
'Malian':'🇲🇱',
'Maltan':'🇲🇹',
'Mexico':'🇲🇽',
'Norway':'🇳🇴',
'Panama':'🇵🇦',
'Poland':'🇵🇱',
'Polish':'🇵🇱',
'Qatari':'🇶🇦',
'Russia':'🇷🇺',
'Rwanda':'🇷🇼',
'Samoan':'🇼🇸',
'Serbia':'🇷🇸',
'Sweden':'🇸🇪',
'Turkey':'🇹🇷',
'Aruba':'🇦🇼',
'Aruba':'🇦🇼',
'Benin':'🇧🇯',
'Chile':'🇨🇱',
'China':'🇨🇳',
'Cuban':'🇨🇺',
'Czech':'🇨🇿',
'Egypt':'🇪🇬',
'Gabon':'🇬🇦',
'Ghana':'🇬🇭',
'Greek':'🇬🇷',
'Haiti':'🇭🇹',
'India':'🇮🇳',
'Iraqi':'🇮🇶',
'Irish':'🇮🇪',
'Italy':'🇮🇹',
'Japan':'🇯🇵',
'Kazak':'🇰🇿',
'Kenya':'🇰🇪',
'Libya':'🇱🇾',
'Macau':'🇲🇴',
'Malta':'🇲🇹',
'Burma':'🇲🇲',
'Nepal':'🇳🇵',
'Dutch':'🇳🇱',
'Niger':'🇳🇪',
'Palau':'🇵🇼',
'Spain':'🇪🇸',
'Qatar':'🇶🇦',
'Samoa':'🇼🇸',
'Saudi':'🇸🇦',
'Sudan':'🇸🇩',
'Swiss':'🇨🇭',
'plane':'✈',
'clock':'⏰',
'urban':'🌆',
'alert':'🚨',
'alarm':'🚨',
'angry':'😠',
'anger':'😠',
'aries':'♈',
'virgo':'♍',
'helps':'👋',
'libra':'♎',
'truck':'🚛',
'drunk':'😲',
'earth':'🌏',
'globe':'🌏',
'koala':'🐨',
'angel':'👼',
'putto':'👼',
'cupid':'👼',
'child':'👶',
'camel':'🐫',
'pound':'💷',
'chart':'📊',
'lager':'🍺',
'bento':'🍱',
'right':'➡',
'books':'📚',
'label':'🔖',
'books':'📚',
'speak':'😮💬',
'bread':'🍞',
'bride':'👰',
'marry':'👰',
'pepsi':'🚏',
'users':'👥',
'Congo':'🇨🇩',
'candy':'🍬',
'sweet':'🍬',
'acorn':'🌰',
'sheep':'🐑',
'santa':'🎅',
'music':'🎶',
'flame':'🔥',
'cross':'⛪',
'beers':'🍻',
'cloud':'☁',
'upset':'😖',
'crown':'👑',
'royal':'👑',
'queen':'👑',
'reach':'🙋',
'teary':'😢',
'gypsy':'🔮',
'early':'🌅',
'curry':'🍛',
'dango':'🍡',
'shops':'🏬',
'darts':'🎯',
'dizzy':'💫',
'lucky':'🍀',
'clash':'💥',
'trash':'🚮',
'puppy':'🐶',
'akita':'🐕',
'donut':'🍩',
'dress':'👗',
'camel':'🐪',
'ruler':'📏',
'water':'💧',
'email':'📧',
'wheat':'🌾',
'world':'🌏',
'globe':'🌏',
'earth':'🌏',
'chick':'🐤',
'torch':'🔦',
'tiger':'🐯',
'tiger':'🐅',
'robot':'😑',
'alien':'👽',
'voted':'☑',
'goofy':'😋',
'silly':'😋',
'kissy':'😘',
'crazy':'😜',
'blank':'😶',
'flame':'🔥',
'punch':'👊',
'blush':'😳',
'foggy':'🌁',
'hatch':'🐣',
'maize':'🌽',
'melon':'🍈',
'lemon':'🍋',
'apple':'🍎',
'peach':'🍑',
'spark':'💥',
'irish':'🍀',
'fries':'🍟',
'prawn':'🍤',
'ghost':'👻',
'ghoul':'👻',
'books':'📚',
'grape':'🍇',
'books':'📚',
'happy':'😀',
'candy':'🍬',
'ghost':'👻',
'skull':'💀',
'death':'💀',
'purse':'👛',
'cupid':'💘',
'heart':'❤',
'check':'✔',
'plant':'🌿',
'tulip':'🌷',
'train':'🚆',
'metro':'🚇',
'knife':'🔪',
'slice':'🔪',
'honey':'🍯',
'horse':'🐎',
'hotel':'🏨',
'watch':'⌚',
'crowd':'👥',
'three':'3⃣',
'house':'🏠',
'devil':'👿',
'inbox':'📥',
'sassy':'💁',
'dolls':'🎎',
'scary':'👹',
'jeans':'👖',
'denim':'👖',
'pants':'👖',
'kissy':'😚',
'koala':'🐨',
'reply':'↩',
'chain':'🔗',
'tears':'😭',
'maple':'🍁',
'melon':'🍈',
'write':'📝',
'notes':'📝',
'metro':'🚇',
'space':'🌌',
'stars':'🌌',
'paper':'📄',
'pager':'📟',
'panda':'🐼',
'peach':'🍑',
'melon':'🍈',
'today':'2⃣📅',
'seven':'7⃣',
'eight':'8⃣',
'happy':'😃',
'happy':'😃',
'smile':'😊',
'snail':'🐌',
'snake':'🐍',
'pasta':'🍝',
'stars':'✨',
'shell':'🐚',
'penis':'🍆',
'rural':'🌾',
'beach':'🐚',
'whale':'🐳',
'tulip':'🌷',
'ramen':'🍜',
'sushi':'🍣',
'phone':'📞',
'tiger':'🐯',
'tiger':'🐅',
'tired':'😫',
'lunch':'🍴',
'dunny':'🚽',
'peach':'🍑',
'groom':'🎩',
'tulip':'🌷',
'rainy':'☔',
'peace':'✌',
'wii u':'🎮',
'watch':'⌚',
'waves':'🌊',
'beach':'🌊',
'melon':'🍈',
'hello':'👋',
'steps':'👣',
'weary':'😩',
'whale':'🐋',
'furin':'🎐',
'winky':'😉',
'foggy':'🌁',
'dingo':'🐺',
'woman':'👩',
'poems':'📜',
'women':'👩',
'soon':'🔜',
'baby':'👶',
'bank':'🏦',
'euro':'💶',
'bath':'🛀',
'nine':'9⃣',
'bear':'🐻',
'beer':'🍺',
'none':'🙅',
'bell':'🔔',
'bike':'🚲',
'bike':'🚴',
'pool':'🎱',
'bird':'🐦',
'cake':'🎂',
'luck':'🍀',
'fugu':'🐡',
'boar':'🐗',
'boar':'🐗',
'bomb':'💣',
'poem':'📜',
'pins':'🎳',
'user':'👤',
'goat':'🐐',
'xmas':'🎄',
'snow':'❄',
'song':'🎶',
'fire':'🔥',
'bell':'🔔',
'baby':'👶',
'girl':'👧',
'four':'4⃣',
'five':'5⃣',
'taco':'🌮',
'dusk':'🌆',
'clap':'👏',
'beer':'🍻',
'loop':'🔁',
'mail':'✉',
'runs':'🏃',
'bang':'💥',
'rice':'🍚',
'amex':'💳',
'croc':'🐊',
'king':'👑',
'tear':'😢',
'flan':'🍮',
'boys':'👦🏾',
'dash':'💨',
'plus':'➕',
'wind':'💨',
'fart':'💨',
'poot':'💨',
'fast':'💨',
'tree':'🌳',
'door':'🚪',
'gown':'👗',
'corn':'🌽',
'crop':'🌾',
'vote':'☑',
'ears':'👂',
'idea':'💡',
'noon':'🕛',
'plug':'🔌',
'tree':'🌲',
'eyes':'👀',
'kiss':'😘',
'paws':'🐾',
'sick':'😷',
'mask':'😷',
'shot':'🎯',
'sars':'😷',
'blue':'😰',
'smog':'🏭',
'fall':'🍂',
'fire':'🔥',
'okay':'👌',
'flex':'💪',
'talk':'😮💬',
'chat':'😀💬',
'file':'📁',
'fire':'🔥',
'fish':'🐟',
'fist':'👊',
'golf':'⛳',
'pear':'🍐',
'feet':'👣',
'foot':'👣',
'step':'👣',
'park':'⛲',
'frog':'🐸',
'pair':'👭',
'frog':'🐸',
'dice':'🎲',
'girl':'👧',
'goat':'🐐',
'cold':'😁',
'fire':'🔥',
'bomb':'💣',
'dead':'💀',
'tool':'🔨',
'ipod':'🎧',
'tick':'✔',
'seat':'💺',
'help':'👋',
'herb':'🌿',
'rose':'🌹',
'home':'🏠',
'love':'❤',
'fire':'🔥',
'lamp':'🏮',
'ogre':'👹',
'kiss':'😚',
'left':'⬅',
'lion':'🐆',
'stop':'🙅',
'tram':'🚊',
'link':'🔗',
'pray':'🙏',
'hope':'🙏',
'lock':'🔒',
'this':'👉',
'male':'👨',
'shoe':'👞',
'meat':'🍖',
'memo':'📝',
'note':'📝',
'oxen':'🐂',
'bull':'🐂',
'page':'📄',
'bear':'🐻',
'butt':'🍑',
'pear':'🍐',
'walk':'🚶',
'cool':'😎',
'smug':'😏',
'like':'👍',
'snow':'❄',
'olaf':'⛄',
'mute':'🔇',
'cool':'🆒',
'free':'🆓',
'beer':'🍺',
'surf':'🏄',
'taxi':'🚕',
'read':'📖',
'tent':'⛺',
'farm':'🚜',
'fish':'🐠',
'jazz':'🎺',
'horn':'🎺',
'rose':'🌹',
'rain':'☔',
'rose':'🌹',
'kiss':'💏',
'ring':'💍',
'xbox':'🎮',
'dick':'🍆',
'wave':'🌊',
'cuts':'✂',
'pear':'🍐',
'wave':'〰',
'bell':'🔔',
'star':'⭐',
'wine':'🍷',
'wink':'😉',
'wife':'👰',
'wolf':'🐺',
'lady':'👩',
'gift':'🎁',
'Cuba':'🇨🇺',
'Fiji':'🇫🇯',
'Guam':'🇬🇺',
'Iran':'🇮🇷',
'Iraq':'🇮🇶',
'Laos':'🇱🇦',
'U.S.':'🇺🇸',
'Mali':'🇲🇱',
'Kiwi':'🇳🇿',
'Niue':'🇳🇺',
'Oman':'🇴🇲',
'Peru':'🇵🇪',
'USA':'🇺🇸',
'yum':'😋',
'ant':'🐜',
'leo':'♌',
'ram':'🐏',
'art':'🎨',
'atm':'🏧',
'car':'🚗',
'yen':'💴',
'nba':'🏀',
'tag':'🔖',
'bug':'🐛',
'bus':'🚌',
'cat':'🐈',
'and':'➕',
'nut':'🌰',
'hen':'🐔',
'ago':'⬅',
'boy':'👦🏾',
'cow':'🐮',
'dog':'🐕',
'dvd':'📀',
'ear':'👂',
'mad':'😤',
'lol':'😂',
'fan':'😍',
'man':'👨',
'add':'➕',
'tie':'👔',
'fax':'📠',
'hot':'🔥',
'fog':'🌁',
'gem':'💎',
'www':'🌐',
'eek':'😬',
'bag':'👜',
'bee':'🐝',
'for':'4⃣',
'tea':'☕',
'imp':'👿',
'oni':'👹',
'key':'🔑',
'arm':'💪',
'war':'💥',
'gun':'🔫',
'dim':'🔅',
'man':'👨',
'box':'📦',
'sad':'😔',
'new':'🆕',
'sos':'🆘',
'six':'6⃣',
'sun':'🌞',
'bar':'🍻',
'yes':'👍',
'sex':'👉👌',
'loo':'🚽',
'see':'👀',
'run':'🏃',
'cut':'✂',
'vhs':'📼',
'day':'📅',
'too':'2⃣',
'two':'2⃣',
'ten':'10⃣',
'vcr':'📼',
'sea':'🌊',
'ski':'🎿',
'fox':'🐺',
'hat':'👒',
'up':'⬆',
'bk':'🏦',
'? ':'❓',
'! ':'❗',
'!!':'‼',
'!?':'⁉',
'et':'👽',
'no':'🙅',
'ok':'👌',
'we':'👭',
'us':'👭',
'cd':'💿',
'ox':'🐂',
'id':'🆔',
'up':'🆙',
'vs':'🆚',
'tv':'📺',
'tm':'™',
'$':'💵',
'€':'💶',
'£':'💷',
'¥':'💴',
'2':'2⃣',
'3':'3⃣',
'4':'4⃣',
'5':'5⃣',
'6':'6⃣',
'7':'7⃣',
'8':'8⃣',
'9':'9⃣',
'10':'10⃣',
'得':'🉐',
'中':'🀄'
}